  version: 2.1

  orbs:
    python: circleci/python@0.3.2

  jobs:

    build-and-test:
      executor: python/default
      steps:
        - checkout
        - python/load-cache
        - run:
            name: Install Dependencies
            command: python3 -m pip install --use-deprecated=legacy-resolver -r requirements.txt
        - python/save-cache
        - run:
            name: Running tests
            command: |
              python3 -m coverage run -m xmlrunner discover -v --output-file test/unit/test_results.xml
              python3 -m coverage report --omit=test/unit/*.py,test/unit/**/*.py
              python3 -m coverage html
              cp htmlcov/index.html htmlcov/._=========================INDEX=========================.html
        - store_test_results:
            name: Store test results
            path: test/unit/test_results.xml
        - store_artifacts:
            name: Store code coverage
            path: htmlcov

  lint-and-coverage:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Coverage
          command: |
            coverage run
            coverage report

  workflows:
    main:
      jobs:
        - build-and-test
